#! /bin/bash

cd ../Daemon
xcodebuild -project CatNip.xcodeproj -configuration Release clean build

cd ../PreferencePane
xcodebuild -project CatNip.xcodeproj -configuration Release clean build

cd ../Installer
rm -rf staging
mkdir staging
mv ../PreferencePane/build/Release/CatNip.prefPane ./staging/CatNip.prefPane
mv ../Daemon/build/Release/CatNip.app ./staging/CatNip.prefPane/Contents/Resources/

rm -rf image
mkdir image
cp -R staging/* image/
cp DS_Store image/.DS_Store
cp background.tiff image/
ln -s /Library/PreferencePanes/ image/PreferencePanes
./pkg-dmg --source image --target CatNip.dmg --attribute V:background.tiff --volname "CatNip" --icon ../Images/CatNip.icns
